# drumscript/__init__.py

"""
DrumScript: A Python-based suite of tools for drum audio analysis and transcription.

This top-level module exposes the primary high-level wrappers for end-to-end 
transcription, as well as the core low-level building blocks for custom DSP pipelines.
"""

import pathlib
from pathlib import Path

from .audio_processor.audio_loader import load_audio, normalise_audio
from .audio_processor.feature_extractor import extract_features
from .audio_processor.onset_detector import detect_onsets
from .audio_processor.stem_splitter import extract_drum_stem, separate_audio
from .audio_processor.tempo_detector import estimate_tempo as _internal_estimate
from .drum_classifier.classify import classify_events
from .notation_generator import midi_exporter, pdf_exporter, xml_exporter

# 1. Import internal functions
from .notation_generator.constants import SAMPLE_RATE
from .notation_generator.score_builder import build_score
from .utils.ffmpeg_installer import install_ffmpeg

# 2. Create user-friendly wrappers

def extract_stems(audio_path, output_dir=None, output_format="wav", drumless=False, mute=None, all_stems=False, full=False):
    """
    Extracts drum stems and optionally separates the full track.

    :param audio_path: Path to the audio file.
    :type audio_path: str
    :param output_dir: Directory to save the output files. Defaults to current working directory.
    :type output_dir: str, optional
    :param output_format: 'wav' or 'mp3', defaults to 'wav'.
    :type output_format: str, optional
    :param drumless: Extract a track with NO drums (plus the isolated drum track).
    :type drumless: bool, optional
    :param mute: List of stems to mute (e.g., ['bass']).
    :type mute: list, optional
    :param all_stems: If True, export all separated stems individually.
    :type all_stems: bool, optional
    :param full: Returns detailed dictionary if True.
    :type full: bool, optional
    :return: Path to the extracted file or a dictionary of results if full=True.
    :rtype: str or dict
    """
    if output_dir is None:
        output_dir = pathlib.Path.cwd() / "stems"
    else:
        output_dir = pathlib.Path(output_dir)

    output_dir.mkdir(parents=True, exist_ok=True)

    result_path = extract_drum_stem(audio_path, output_dir=str(output_dir))

    results = separate_audio(
        input_audio_path=audio_path,
        output_format=output_format,
        drumless=drumless,
        mute=mute,
        all_stems=all_stems,
        output_dir=str(output_dir)
    )

    if full:
        return {
            "status": "success",
            "drum_stem_path": result_path,
            "original_file": audio_path,
            "output_directory": str(output_dir)
        }

    return result_path or results.get('drums') or results.get('drums_stem')


def detect_tempo(audio_input, full=False):
    """
    Estimates the tempo (BPM) of a given audio file or audio array.

    :param audio_input: File path OR loaded audio data array.
    :type audio_input: str or np.ndarray
    :param full: Return detailed stats dictionary if True.
    :type full: bool, optional
    :return: The estimated BPM (float) or a dictionary of stats.
    :rtype: float or dict
    """
    if isinstance(audio_input, str):
        y, sr = load_audio(audio_input, sr=SAMPLE_RATE)
        # y, sr = load_audio(audio_input)
        y = normalise_audio(y)
    else:
        y = audio_input
        sr = SAMPLE_RATE

    bpm = _internal_estimate(y, sr)

    if full:
        return {"bpm": bpm, "sr": sr}
    return bpm


def export_pdf(score, output_path=None, **kwargs):
    """
    Exports a generated DrumScript score object to a PDF file.

    :param score: The score object generated by build_score().
    :type score: object
    :param output_path: The exact file path to save the PDF. Defaults to 'drumscript.pdf' in CWD.
    :type output_path: str, optional
    :return: The path to the generated PDF.
    :rtype: str
    """
    if output_path is None:
        #output_path = pathlib.Path.cwd() / "drum_score.pdf"
        output_path = pathlib.Path.cwd() / "drumscript.pdf"

    return pdf_exporter.export_pdf(score, output_path=output_path, **kwargs)


def export_midi(score, output_path=None, **kwargs):
    """
    Exports a generated DrumScript score object to a MIDI file.

    :param score: The score object generated by build_score().
    :type score: object
    :param output_path: The exact file path to save the MIDI. Defaults to 'drumscript.mid' in CWD.
    :type output_path: str, optional
    :return: The path to the generated MIDI file.
    :rtype: str
    """
    if output_path is None:
        #output_path = pathlib.Path.cwd() / "drum_score.mid"
        output_path = pathlib.Path.cwd() / "drumscript.mid"

    return midi_exporter.export_midi(score, output_path=output_path, **kwargs)


def export_xml(score, output_path=None, **kwargs):
    """
    Exports a generated DrumScript score object to a MusicXML file.

    :param score: The music21.stream.Score object generated by build_score().
    :type score: object
    :param output_path: The exact file path to save the XML. Defaults to 'drumscript.xml' in CWD.
    :type output_path: str, optional
    :return: The path to the generated XML file.
    :rtype: str
    """
    #if output_path is None:
     #   output_path = pathlib.Path.cwd() / "drum_score.xml"


    # 1. Handle output routing
    if output_path is None:
        #xml_path = Path.cwd() / "drum_score.xml"
        xml_path = Path.cwd() / "drumscript.xml"
    else:
        xml_path = Path(output_path)

    return xml_exporter.export_xml(score, output_path=output_path, **kwargs)



# 3. Explicitly define the Public API (Used by Sphinx and `from drumscript import *`)
__all__ = [
    # High-level wrappers
    "extract_stems",
    "detect_tempo",
    "export_pdf",
    "export_midi",
    "export_xml",

    # Core DSP & Classification pipeline
    "load_audio",
    "normalise_audio",
    "detect_onsets",
    "extract_features",
    "classify_events",
    "classify_rudiment_events",
    "build_score",

    # Utilities
    "install_ffmpeg",
]

__version__ = "0.1.2"
