# DrumScript/notation_generator/pdf_exporter.py

import os
import music21
import subprocess # We need subprocess to call LilyPond externally

def generate_pdf(music21_score: music21.stream.Score, output_filepath: str):
    """
    Generates a PDF document of the drum sheet music from a music21 Score object
    by first creating MusicXML using music21, and then converting it to PDF using LilyPond.

    Args:
        music21_score (music21.stream.Score): The music21 Score object containing the drum notation.
        output_filepath (str): The full path where the PDF file should be saved.
    """
    if not music21_score:
        print("No music21 score provided to generate PDF.")
        return

    print(f"Generating PDF for '{music21_score.metadata.title}' to {output_filepath} using music21 (for XML) and LilyPond (for PDF)...")

    # Ensure output directory exists
    output_dir = os.path.dirname(output_filepath)
    os.makedirs(output_dir, exist_ok=True)

    # Temporarily save as MusicXML. LilyPond will read this file.
    musicxml_filepath = output_filepath.replace('.pdf', '.musicxml')

    try:
        # Step 1: Music21 writes the score to a MusicXML file
        music21_score.write('musicxml', fp=musicxml_filepath)
        print(f"MusicXML saved to: {musicxml_filepath}")

        # Step 2: Call LilyPond externally to convert the MusicXML to PDF
        lilypond_path = '/opt/homebrew/bin/lilypond' # Your confirmed LilyPond path

        # LilyPond command to convert MusicXML to PDF:
        # lilypond --pdf [input_file.musicxml]
        # LilyPond will automatically create a PDF with the same base name
        # (e.g., 'my_drum_score__new.pdf') in the same directory as the input XML.
        lilypond_command = [
            lilypond_path,
            '--pdf',              # This option tells LilyPond to output a PDF file
            musicxml_filepath     # The input MusicXML file generated by music21
        ]

        print(f"Executing LilyPond command: {' '.join(lilypond_command)}")
        
        # Run the LilyPond command. check=True will raise an exception if LilyPond returns a non-zero exit code.
        # capture_output=True and text=True help in debugging by capturing stdout/stderr.
        subprocess.run(lilypond_command, check=True, text=True, capture_output=True)

        print(f"PDF successfully saved to: {output_filepath}")

    except FileNotFoundError:
        # This specific error occurs if the lilypond_path executable itself is not found.
        print(f"Error: LilyPond executable not found at '{lilypond_path}'.")
        print("Please ensure LilyPond is installed and the path is correct.")
        raise # Re-raise to halt execution and signal failure
    except subprocess.CalledProcessError as e:
        # This error occurs if LilyPond was found, but it failed during conversion (e.g., malformed XML, internal LilyPond error).
        print(f"Error during LilyPond conversion (exit code {e.returncode}):")
        print(f"Command executed: {' '.join(e.cmd)}")
        print(f"LilyPond STDOUT:\n{e.stdout}")
        print(f"LilyPond STDERR:\n{e.stderr}")
        print("Please ensure the generated MusicXML file is valid and LilyPond can process it.")
        raise # Re-raise
    except music21.converter.ConverterException as e:
        # This error is from music21 itself, typically if it fails to write the MusicXML.
        print(f"Error during music21 MusicXML export: {e}")
        print("This indicates an issue with the music21 score object or its internal MusicXML converter.")
        raise
    except Exception as e:
        # Catch any other unexpected errors
        print(f"An unexpected error occurred during PDF generation: {e}")
        import traceback
        traceback.print_exc() # Print full stack trace for debugging
        raise
    finally:
        # --- TEMPORARILY COMMENT OUT THIS BLOCK FOR DEBUGGING ---
        # if os.path.exists(musicxml_filepath):
        #     os.remove(musicxml_filepath)
        #     print(f"Cleaned up temporary MusicXML file: {musicxml_filepath}")
        pass # Keep this 'pass' if you comment out the block
    
def export_to_xml(music21_score: music21.stream.Score, output_filepath: str):
    """
    Exports a music21 Score object to a MusicXML file.

    Args:
        music21_score (music21.stream.Score): The music21 Score object.
        output_filepath (str): The full path where the .xml file should be saved.
    """
    if not music21_score:
        print("No music21 score provided to export to XML.")
        return

    try:
        # Ensure output directory exists
        output_dir = os.path.dirname(output_filepath)
        os.makedirs(output_dir, exist_ok=True)
        
        music21_score.write('musicxml', fp=output_filepath)
        print(f"MusicXML successfully saved to: {output_filepath}")
        
    except music21.converter.ConverterException as e:
        print(f"Error during music21 MusicXML export: {e}")
        raise
    except Exception as e:
        print(f"An unexpected error occurred during XML export: {e}")
        raise