# DrumScript/notation_generator/pdf_exporter.py

import os
try:
    from reportlab.pdfgen import canvas
    from reportlab.lib.pagesizes import A4
    from reportlab.lib import colors
except ImportError:
    print("Error: 'reportlab' library not found. Please run 'pip install reportlab'")
    # We don't exit here to allow the module to be imported, but export will fail
    canvas = None

import music21
from drumscript.notation_generator import constants

# --- Configuration Constants ---
PAGE_WIDTH, PAGE_HEIGHT = A4
MARGIN_X = 50
MARGIN_Y = 50
STAFF_SPACING = 100 # Distance between systems
LINE_SPACING = 6    # Distance between staff lines
NOTE_SPACING_BASE = 30 # Pixels per beat (variable based on density)

# Reference Pitch: The note that sits on the middle line (Line 3)
# For standard percussion clef, this is often arbitrary, but let's pick B3 as middle
REF_PITCH_MIDDLE_LINE = music21.pitch.Pitch('B3')


def get_vertical_position(staff_position_str: str, staff_y_base: float) -> float:
    """
    Calculates the Y-coordinate for a note based on its staff position string (e.g. 'F2', 'C3').
    """
    if not staff_position_str:
        return staff_y_base + (2 * LINE_SPACING) # Default to middle
        
    target_pitch = music21.pitch.Pitch(staff_position_str)
    
    # Calculate diatonic steps between target and reference
    # Positive = higher, Negative = lower
    # We use diatonicNoteNum to ignore accidentals/semitones (visual height only)
    steps_diff = target_pitch.diatonicNoteNum - REF_PITCH_MIDDLE_LINE.diatonicNoteNum
    
    # Each step is half the line spacing (line -> space -> line)
    y_offset = steps_diff * (LINE_SPACING / 2)
    
    # staff_y_base is the BOTTOM line (Line 1). 
    # Middle line (Line 3) is at staff_y_base + (2 * LINE_SPACING)
    middle_line_y = staff_y_base + (2 * LINE_SPACING)
    
    return middle_line_y + y_offset


def draw_staff(c, x, y, width):
    """Draws the 5 lines of the percussion staff."""
    c.setLineWidth(1)
    c.setStrokeColor(colors.black)
    for i in range(5):
        line_y = y + (i * LINE_SPACING)
        c.line(x, line_y, x + width, line_y)
        
    # Draw "Percussion" Clef (Simple Rectangle for now)
    c.rect(x, y, 10, 4 * LINE_SPACING, fill=1) # Solid block at start
    c.rect(x + 12, y + LINE_SPACING, 4, 2 * LINE_SPACING, fill=1) 


def draw_note(c, x, y, note_type):
    """Draws a notehead at the specified position."""
    # Notehead size
    r = 3.5 
    
    if note_type == 'x' or note_type == 'circle-x':
        # Draw X
        c.setLineWidth(2)
        c.line(x - r, y - r, x + r, y + r)
        c.line(x - r, y + r, x + r, y - r)
        # For open hi-hat (circle-x), add a circle
        if note_type == 'circle-x':
            c.setLineWidth(1)
            c.circle(x, y, r + 2, stroke=1, fill=0)
    else:
        # Draw Normal Notehead (Oval)
        c.saveState()
        c.translate(x, y)
        c.scale(1.2, 0.8) # Squish circle to make an oval
        c.circle(0, 0, r, fill=1, stroke=0)
        c.restoreState()
        
    # Draw Stem (Simple Upward Stem)
    c.setLineWidth(1)
    stem_height = 25
    c.line(x + r, y, x + r, y + stem_height)


def generate_custom_pdf(detected_events, output_filepath, tempo=120):
    """
    Generates a PDF drum score purely using Python (ReportLab).
    Does NOT require external software.
    """
    if canvas is None:
        print("❌ Cannot generate PDF: ReportLab library is missing.")
        return

    print(f"Generating Native PDF Score: {output_filepath}")
    
    c = canvas.Canvas(output_filepath, pagesize=A4)
    c.setTitle("DrumScript Transcription")
    
    # --- Header ---
    c.setFont("Helvetica-Bold", 24)
    c.drawString(MARGIN_X, PAGE_HEIGHT - 50, "DrumScript Transcription")
    c.setFont("Helvetica", 12)
    c.drawString(MARGIN_X, PAGE_HEIGHT - 70, f"Tempo: {int(tempo)} BPM")
    c.drawString(MARGIN_X, PAGE_HEIGHT - 85, "Generated by DrumScript AI")
    
    # --- Layout Calculation ---
    current_y = PAGE_HEIGHT - 150
    current_x = MARGIN_X + 30 # Start after clef
    system_width = PAGE_WIDTH - (2 * MARGIN_X)
    
    # Draw First System Staff
    draw_staff(c, MARGIN_X, current_y, system_width)
    
    # Calculate pixels per second based on spacing and tempo
    # 120 BPM = 2 beats/sec. If 30px/beat -> 60px/sec
    pixels_per_beat = NOTE_SPACING_BASE
    beats_per_second = tempo / 60.0
    pixels_per_second = pixels_per_beat * beats_per_second

    last_event_time = 0
    
    # Sort events by time just in case
    detected_events.sort(key=lambda x: x['time'])
    
    # --- Event Loop ---
    for event in detected_events:
        time_sec = event['time']
        drum_types = event['drums']
        
        # Calculate X position relative to start of line
        # Ideally we track "cursor" x. 
        # Simple Approach: Move cursor by delta time
        dt = time_sec - last_event_time
        dx = dt * pixels_per_second
        
        # Ensure minimum spacing so notes don't overlap
        if dx < 15 and dt > 0: dx = 15 
        
        current_x += dx
        
        # CHECK FOR LINE WRAP
        if current_x > (MARGIN_X + system_width - 20):
            # Move to next system
            current_y -= STAFF_SPACING
            current_x = MARGIN_X + 30
            
            # Check for Page Wrap
            if current_y < MARGIN_Y:
                c.showPage() # New Page
                current_y = PAGE_HEIGHT - 100
                
                # Redraw Header (Optional)
                c.setFont("Helvetica", 10)
                c.drawString(MARGIN_X, PAGE_HEIGHT - 50, "DrumScript Transcription (Cont.)")
            
            # Draw Staff for new line
            draw_staff(c, MARGIN_X, current_y, system_width)
            
        # DRAW NOTES
        # We might have multiple drums at the same time (Chord)
        for drum_type in drum_types:
            # Get info from map
            d_map = constants.DRUM_NOTATION_MAP.get(drum_type, constants.DRUM_NOTATION_MAP['kick'])
            staff_pos = d_map.get('staff_position', 'F2')
            note_head = d_map.get('note_head', 'normal')
            
            # Calculate Y
            note_y = get_vertical_position(staff_pos, current_y)
            
            # Render
            draw_note(c, current_x, note_y, note_head)
            
        last_event_time = time_sec

    c.save()
    print(f"Native PDF successfully saved to: {output_filepath}")
