# DrumScript/notation_generator/pdf_exporter.py

import os
import music21
import subprocess # We need subprocess to call LilyPond externally
from pathlib import Path

# OLD BLOCK, KEEP FOR NOW, TIDY UP LATER
"""def generate_pdf(music21_score: music21.stream.Score, output_filepath: str):

    # Generates a PDF document of the drum sheet music from a music21 Score object
    # by first creating MusicXML using music21, and then converting it to PDF using LilyPond.
    # Args:
     #   music21_score (music21.stream.Score): The music21 Score object containing the drum notation.
     #   output_filepath (str): The full path where the PDF file should be saved.

    if not music21_score:
        print("No music21 score provided to generate PDF.")
        return

    print(f"Generating PDF for '{music21_score.metadata.title}' to {output_filepath} using music21 (for XML) and LilyPond (for PDF)...")

    # Ensure output directory exists
    output_dir = os.path.dirname(output_filepath)
    os.makedirs(output_dir, exist_ok=True)

    # Temporarily save as MusicXML. LilyPond will read this file.
    musicxml_filepath = output_filepath.replace('.pdf', '.musicxml')

    try:
        # Step 1: Music21 writes the score to a MusicXML file
        music21_score.write('musicxml', fp=musicxml_filepath)
        print(f"MusicXML saved to: {musicxml_filepath}")

        # Step 2: Call LilyPond externally to convert the MusicXML to PDF
        lilypond_path = '/opt/homebrew/bin/lilypond' # Your confirmed LilyPond path

        # LilyPond command to convert MusicXML to PDF:
        # lilypond --pdf [input_file.musicxml]
        # LilyPond will automatically create a PDF with the same base name
        # (e.g., 'my_drum_score__new.pdf') in the same directory as the input XML.
        lilypond_command = [
            lilypond_path,
            '--pdf',              # This option tells LilyPond to output a PDF file
            musicxml_filepath     # The input MusicXML file generated by music21
        ]

        print(f"Executing LilyPond command: {' '.join(lilypond_command)}")
        
        # Run the LilyPond command. check=True will raise an exception if LilyPond returns a non-zero exit code.
        # capture_output=True and text=True help in debugging by capturing stdout/stderr.
        subprocess.run(lilypond_command, check=True, text=True, capture_output=True)

        print(f"PDF successfully saved to: {output_filepath}")

    except FileNotFoundError:
        # This specific error occurs if the lilypond_path executable itself is not found.
        print(f"Error: LilyPond executable not found at '{lilypond_path}'.")
        print("Please ensure LilyPond is installed and the path is correct.")
        raise # Re-raise to halt execution and signal failure
    except subprocess.CalledProcessError as e:
        # This error occurs if LilyPond was found, but it failed during conversion (e.g., malformed XML, internal LilyPond error).
        print(f"Error during LilyPond conversion (exit code {e.returncode}):")
        print(f"Command executed: {' '.join(e.cmd)}")
        print(f"LilyPond STDOUT:\n{e.stdout}")
        print(f"LilyPond STDERR:\n{e.stderr}")
        print("Please ensure the generated MusicXML file is valid and LilyPond can process it.")
        raise # Re-raise
    except music21.converter.ConverterException as e:
        # This error is from music21 itself, typically if it fails to write the MusicXML.
        print(f"Error during music21 MusicXML export: {e}")
        print("This indicates an issue with the music21 score object or its internal MusicXML converter.")
        raise
    except Exception as e:
        # Catch any other unexpected errors
        print(f"An unexpected error occurred during PDF generation: {e}")
        import traceback
        traceback.print_exc() # Print full stack trace for debugging
        raise
    finally:
        # --- TEMPORARILY COMMENT OUT THIS BLOCK FOR DEBUGGING ---
        # if os.path.exists(musicxml_filepath):
        #     os.remove(musicxml_filepath)
        #     print(f"Cleaned up temporary MusicXML file: {musicxml_filepath}")
        pass # Keep this 'pass' if you comment out the block"""


# latest block
def generate_pdf(score: music21.stream.Score, output_filepath: str):
    """
    Exports a music21 score to both MusicXML and PDF formats.
    
    It saves:
    1. A .musicxml file (at the same path, with .musicxml extension)
    2. A .pdf file (at the specified output_filepath)
    
    Args:
        score (music21.stream.Score): The music21 score object to be exported.
        output_filepath (str): The full path for the final .pdf file.
                               e.g., "outputs/my_song.pdf"
    """
    
    # --- 1. Define File Paths ---
    output_path = Path(output_filepath)
    
    # Get the directory to save in, e.g., "outputs/"
    output_dir = output_path.parent
    
    # Get the base filename, e.g., "my_song_transcription"
    file_stem = output_path.stem
    
    # Define the .xml path, e.g., "outputs/my_song_transcription.musicxml"
    xml_path = output_dir / f"{file_stem}.musicxml"
    
    # Create the output directory if it doesn't exist
    output_dir.mkdir(parents=True, exist_ok=True)

    # --- 2. Export the MusicXML file ---
    try:
        xml_filepath_str = str(xml_path)
        print(f"Saving MusicXML to: {xml_filepath_str}...")
        score.write('musicxml', fp=xml_filepath_str)
        print(f"Successfully saved {xml_filepath_str}")
        
    except Exception as e:
        print(f"ERROR: Failed to save MusicXML file: {e}")
        # We can still try to generate the PDF
    
    # --- 3. Export the PDF file ---
    # This single command tells music21 to:
    # 1. Convert the score to a temporary .ly file
    # 2. Call LilyPond on that .ly file
    # 3. Save the final .pdf to our desired path
    try:
        print(f"Generating PDF (via LilyPond) to: {output_filepath}...")
        score.write('pdf', fp=output_filepath)
        print(f"Successfully generated {output_filepath}")
        
    except Exception as e:
        print(f"ERROR: Failed to generate PDF with LilyPond.")
        print("Please ensure LilyPond is installed and accessible in your system's PATH.")
        # Re-raise the error to stop the script
        raise e
    
def export_to_xml(music21_score: music21.stream.Score, output_filepath: str):
    """
    Exports a music21 Score object to a MusicXML file.

    Args:
        music21_score (music21.stream.Score): The music21 Score object.
        output_filepath (str): The full path where the .xml file should be saved.
    """
    if not music21_score:
        print("No music21 score provided to export to XML.")
        return

    try:
        # Ensure output directory exists
        output_dir = os.path.dirname(output_filepath)
        os.makedirs(output_dir, exist_ok=True)
        
        music21_score.write('musicxml', fp=output_filepath)
        print(f"MusicXML successfully saved to: {output_filepath}")
        
    except music21.converter.ConverterException as e:
        print(f"Error during music21 MusicXML export: {e}")
        raise
    except Exception as e:
        print(f"An unexpected error occurred during XML export: {e}")
        raise