# drumscript/notation_generator/xml_exporter.py

"""
Module for rendering the drum score to MusicXML format.
MusicXML is the industry standard for sharing sheet music between 
applications like Sibelius, Guitar Pro, Logic, Cubase, or MuseScore.
"""

from pathlib import Path
import music21
from datetime import datetime

# print("\n# ------------------------------------------------------------------------------------")
# datetimestamp = datetime.now()
# print(f'\ndate/time: {datetimestamp}')

def export_xml(score, output_path=None):
    """
    Exports a generated DrumScript score object to a MusicXML file.

    :param score: The music21.stream.Score object generated by build_score().
    :type score: object
    :param output_path: The exact file path to save the XML. Defaults to 'drum_score.xml' in CWD.
    :type output_path: str, optional
    :return: The path to the generated XML file.
    :rtype: str
    """
    
    # 1. Handle Pandas-style output routing
    if output_path is None:
        xml_path = Path.cwd() / "drum_score.xml"
    else:
        xml_path = Path(output_path)
        
    # Ensure the parent directory of the requested file path exists
    xml_path.parent.mkdir(parents=True, exist_ok=True)
    output_filepath = str(xml_path)

    print(f"Generating MusicXML: {output_filepath}")

    # 2. Use music21's built-in MusicXML writer
    try:
        # music21's score.write() natively handles the XML translation
        score.write("musicxml", fp=output_filepath)
        print(f"MusicXML successfully saved to: {output_filepath}")
        return output_filepath
        
    except Exception as e:
        print(f"Failed to generate MusicXML: {e}")
        return None