name: Run Tests

# Trigger the workflow on push or pull request to main
on:
  push:
    branches: [ "main", "build/pypi_assets" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Test across multiple Python versions to ensure the package is robust
        python-version: ["3.9", "3.10", "3.11", "3.12","3.13"] # consistent with versions in uv.lock. Removed 3.14 from list given its infancy (ie bleeding-edge status)

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Linux System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libportaudio2 libsndfile1 ffmpeg

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "latest"

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        # Installs package in editable mode plus the 'test' optional dependencies
        uv pip install --system -e ".[test]"

    #- name: Lint with Flake8
     # run: |
        # Stop the build if there are Python syntax errors or undefined names
      #  uv pip install --system flake8
       # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # treat all errors as warnings for now (exit-zero)
        #flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests with pytest
      run: |
        pytest